# Generated by Django 5.1.6 on 2025-05-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("certificates", "0002_course_ocrextraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="file_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
